---
title: Pavitra's World
timezone: Asia/Kolkata
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Explore my whole new world
show_downloads: false
baseurl: 
url: https://pavi2410.tk
disqus_shortname: pavi-tk
google_analytics: UA-92654291-1
cayman-blog:
  date_format: "%b %d, %Y"
theme: 
author: Pavitra Golchha
image: "/thumbnail-jumbo.png"
social:
  twitter: PavitraGolchha
  gplus: "+PavitraGolchha"
  fb: pavi2410
